name: "Deploy Gradle Package"
description: "Deploys Gradle Package"
inputs:
  java-version:
    default: 17
    description: "Version of Java to build with"
  java-distribution:
    default: "temurin"
    description: "Distribution of Java to use"
  secret-token:
    required: true
    description: "GITHUB_TOKEN secret - needed auth to publish"
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4.2.1
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin
        
    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.secret-token }}
